/** Catálogos espelhados de app-tumulos.js */

export const PEDRA_LABELS = {
  tampa: 'Tampa',
  detalhe: 'Detalhe Superior',
  laterais: 'Laterais (×2)',
  frontais: 'Frontais (×2)',
  base: 'Base',
  gavetas: 'Frentes de Gaveta',
  moldura: 'Moldura (ml)',
  pingadeira: 'Pingadeira (ml)',
  sainha: 'Sainha',
  recortes: 'Recortes / Furos',
};

export const MDO_LABELS = {
  marmorista: 'Marmorista',
  ajudante: 'Ajudante',
  instalacao: 'Instalação',
  acabamento: 'Acabamento',
  montagem: 'Montagem',
  transporte: 'Transporte',
  riscoQuebra: 'Risco de Quebra (%)',
  dificuldade: 'Dificuldade (%)',
};

export const OBRA_LABELS = {
  fundacao: 'Fundação',
  levantamento: 'Levantamento de Alvenaria',
  reboco: 'Reboco / Chapisco',
  contraPiso: 'Contra-piso',
  gavetas: 'Gavetas (estrutura)',
  concreto: 'Concreto Armado',
  acabOb: 'Acabamento Final',
};

export const MAT_LABELS = {
  cimento: 'Cimento',
  areia: 'Areia',
  brita: 'Brita',
  ferro: 'Ferro / Tela',
  tijolos: 'Tijolos',
  blocos: 'Blocos de Concreto',
  massa: 'Massa Pronta',
  cola: 'Cola p/ Granito',
  rejunte: 'Rejunte',
  agua: 'Água (caminhão)',
  frete: 'Frete',
};

export const ACAB_LABELS = {
  polimento: 'Polimento Especial',
  bisote: 'Borda Bisotada',
  jateamento: 'Jateamento',
  resinagem: 'Resina Impermeabilizante',
  furo: 'Furo / Recorte',
  chanfro: 'Chanfro Decorativo',
};

export const TUM_TIPOS = {
  simples: {
    label: 'Túmulo Simples',
    icon: '⬛',
    desc: 'Sugestão inicial: tampa, laterais, frontais, base.',
    dims: { comp: 2.2, larg: 0.9, alt: 0.6, esp: 3, gavetas: 1 },
    pedras: ['tampa', 'laterais', 'frontais', 'base'],
    mdo: ['marmorista', 'ajudante', 'instalacao', 'acabamento', 'transporte', 'riscoQuebra'],
    obra: ['fundacao'],
    mat: ['cimento', 'areia', 'massa', 'cola', 'rejunte'],
    diasMdo: 2,
    diasObra: 2,
    tempoTotal: 4,
  },
  personalizado: {
    label: 'Projeto sob medida',
    icon: '✏️',
    desc: 'Sem itens marcados — defina pedra, obra, materiais e acabamentos nas abas.',
    dims: { comp: 2.2, larg: 0.9, alt: 0.6, esp: 3, gavetas: 1 },
    pedras: [],
    mdo: [],
    obra: [],
    mat: [],
    diasMdo: 2,
    diasObra: 0,
    tempoTotal: 2,
  },
  gaveta_dupla: {
    label: 'Gaveta Dupla',
    icon: '📦',
    desc: 'Sugestão: 2 compartimentos; ajuste medidas e composição nas abas.',
    dims: { comp: 2.2, larg: 0.9, alt: 1.2, esp: 3, gavetas: 2 },
    pedras: ['tampa', 'laterais', 'frontais', 'gavetas', 'base'],
    mdo: ['marmorista', 'ajudante', 'instalacao', 'acabamento', 'montagem', 'transporte', 'riscoQuebra'],
    obra: ['fundacao', 'levantamento', 'reboco', 'gavetas'],
    mat: ['cimento', 'areia', 'brita', 'tijolos', 'massa', 'cola', 'rejunte'],
    diasMdo: 4,
    diasObra: 5,
    tempoTotal: 9,
  },
  gaveta_tripla: {
    label: 'Gaveta Tripla',
    icon: '🗃️',
    desc: 'Sugestão: 3 compartimentos — tudo editável.',
    dims: { comp: 2.4, larg: 0.9, alt: 1.8, esp: 3, gavetas: 3 },
    pedras: ['tampa', 'laterais', 'frontais', 'gavetas', 'base', 'moldura'],
    mdo: ['marmorista', 'ajudante', 'instalacao', 'acabamento', 'montagem', 'transporte', 'riscoQuebra', 'dificuldade'],
    obra: ['fundacao', 'levantamento', 'reboco', 'gavetas', 'concreto'],
    mat: ['cimento', 'areia', 'brita', 'ferro', 'tijolos', 'blocos', 'massa', 'cola', 'rejunte'],
    diasMdo: 6,
    diasObra: 7,
    tempoTotal: 13,
  },
  capela: {
    label: 'Capela / Monumento',
    icon: '⛪',
    desc: 'Sugestão monumental — personalize dimensões e peças.',
    dims: { comp: 2.6, larg: 1.6, alt: 2.2, esp: 3, gavetas: 2 },
    pedras: ['tampa', 'detalhe', 'laterais', 'frontais', 'gavetas', 'base', 'moldura', 'pingadeira', 'sainha'],
    mdo: ['marmorista', 'ajudante', 'instalacao', 'acabamento', 'montagem', 'transporte', 'riscoQuebra', 'dificuldade'],
    obra: ['fundacao', 'levantamento', 'reboco', 'contraPiso', 'gavetas', 'concreto', 'acabOb'],
    mat: ['cimento', 'areia', 'brita', 'ferro', 'tijolos', 'blocos', 'massa', 'cola', 'rejunte', 'agua', 'frete'],
    diasMdo: 12,
    diasObra: 15,
    tempoTotal: 27,
  },
  revestimento: {
    label: 'Revestimento / Reforma Pedra',
    icon: '🪨',
    desc: 'Foco em pedra na estrutura existente — altere peças e m² à vontade.',
    dims: { comp: 2.2, larg: 0.9, alt: 0.8, esp: 2, gavetas: 1 },
    pedras: ['tampa', 'laterais', 'frontais', 'moldura', 'recortes'],
    mdo: ['marmorista', 'ajudante', 'acabamento', 'transporte', 'riscoQuebra'],
    obra: [],
    mat: ['cola', 'rejunte'],
    diasMdo: 2,
    diasObra: 0,
    tempoTotal: 2,
  },
  reforma: {
    label: 'Reforma Completa',
    icon: '🔧',
    desc: 'Sugestão para reforma — amplie ou reduza o escopo nas abas.',
    dims: { comp: 2.2, larg: 0.9, alt: 0.8, esp: 3, gavetas: 1 },
    pedras: ['tampa', 'laterais', 'frontais', 'base'],
    mdo: ['marmorista', 'ajudante', 'instalacao', 'acabamento', 'transporte', 'riscoQuebra'],
    obra: ['fundacao', 'reboco'],
    mat: ['cimento', 'areia', 'massa', 'cola', 'rejunte'],
    diasMdo: 3,
    diasObra: 2,
    tempoTotal: 5,
  },
  jazigo: {
    label: 'Jazigo Completo',
    icon: '🏛️',
    desc: 'Sugestão jazigo grande — número de compartimentos é livre.',
    dims: { comp: 3.0, larg: 2.0, alt: 2.4, esp: 4, gavetas: 4 },
    pedras: ['tampa', 'detalhe', 'laterais', 'frontais', 'gavetas', 'base', 'moldura', 'pingadeira', 'sainha'],
    mdo: ['marmorista', 'ajudante', 'instalacao', 'acabamento', 'montagem', 'transporte', 'riscoQuebra', 'dificuldade'],
    obra: ['fundacao', 'levantamento', 'reboco', 'contraPiso', 'gavetas', 'concreto', 'acabOb'],
    mat: ['cimento', 'areia', 'brita', 'ferro', 'tijolos', 'blocos', 'massa', 'cola', 'rejunte', 'agua', 'frete'],
    diasMdo: 16,
    diasObra: 20,
    tempoTotal: 36,
  },
};

/** Pedras de exemplo (substituir pela CFG real na integração) */
export const SAMPLE_STONES = [
  { id: 'st1', nm: 'Granito simples nacional', pr: 220 },
  { id: 'st2', nm: 'Granito padrão', pr: 320 },
  { id: 'st3', nm: 'Granito premium', pr: 520 },
];
